import 'package:flutter/material.dart';

class Product {
  final String? image, title, origin, description;
  final int? price, age, id;
  final Color? color;

  Product({
    this.id,
    this.image,
    this.title,
    this.price,
    this.origin,
    this.description,
    this.age,
    this.color,
  });
}

List<Product> products = [
  Product(
      id: 1,
      title: "Toy Dog",
      price: 250,
      origin: "BD",
      age: 3,
      description: dummyText,
      image: "assets/images/toy_1.png",
      color: Color(0xFFCCB28D)),
  Product(
      id: 2,
      title: "Toy Doll",
      price: 300,
      origin: "USA",
      age: 3,
      description: dummyText,
      image: "assets/images/toy_2.png",
      color: Color(0xFFF5E773)),
  Product(
      id: 3,
      title: "Dinosor",
      price: 350,
      origin: "CN",
      age: 3,
      description: dummyText,
      image: "assets/images/toy_3.png",
      color: Color(0xFF9ABD44)),
  Product(
      id: 4,
      title: "Trnsparent Dinosor",
      price: 250,
      origin: "BD",
      age: 5,
      description: dummyText,
      image: "assets/images/toy_4.png",
      color: Color(0xFF70E66C)),
  Product(
      id: 5,
      title: "Toy Joker",
      price: 600,
      origin: "USA",
      age: 5,
      description: dummyText,
      image: "assets/images/toy_5.png",
      color: Color(0xFFFB7883)),
  Product(
    id: 6,
    title: "Toy horse",
    price: 250,
    origin: "IND",
    age: 2,
    description: dummyText,
    image: "assets/images/toy_6.png",
    color: Color(0xFFBA855A),
  ),
  Product(
    id: 7,
    title: "Plastic Toy",
    price: 180,
    origin: "BD",
    age: 2,
    description: dummyText,
    image: "assets/images/toy_7.png",
    color: Color(0xFFF7EF8D),
  ),
  Product(
    id: 8,
    title: "Egg toy",
    price: 150,
    origin: "BD",
    age: 2,
    description: dummyText,
    image: "assets/images/toy_8.png",
    color: Color(0xFFF7EF8D),
  ),
  Product(
    id: 9,
    title: "Toy Worm",
    price: 200,
    origin: "USA",
    age: 4,
    description: dummyText,
    image: "assets/images/toy_9.png",
    color: Color(0xFFF2B576),
  ),
  Product(
    id: 10,
    title: "Plastic toy",
    price: 200,
    origin: "CN",
    age: 3,
    description: dummyText,
    image: "assets/images/toy_10.png",
    color: Color(0xFFF2B576),
  ),
  Product(
    id: 11,
    title: "Toy Bike",
    price: 500,
    origin: "CN",
    age: 3,
    description: dummyText,
    image: "assets/images/toy_11.png",
    color: Color(0xFFE26B40),
  ),
  Product(
    id: 12,
    title: "Toy tomy",
    price: 600,
    origin: "USA",
    age: 2,
    description: dummyText,
    image: "assets/images/toy_12.png",
    color: Color(0xFFEB9392),
  ),
  Product(
    id: 13,
    title: "Toy doll",
    price: 500,
    origin: "CN",
    age: 2,
    description: dummyText,
    image: "assets/images/toy_13.png",
    color: Color(0xFFEB9392),
  ),
  Product(
    id: 14,
    title: "Plastic Toy",
    price: 400,
    origin: "BD",
    age: 3,
    description: dummyText,
    image: "assets/images/toy_14.png",
    color: Color(0xFFAAC585),
  ),
];

String dummyText =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.";
